### ISSUE TITLE
Component dependencies in ring-enabled libraries

### ISSUE THREAD

**Issue by kendagriff** [weavejester/duct#10]
So, asking for advice: I've stumbled across this a couple times while using `duct` alongside ring-enabled middleware, but in this recent situation, I can't find an adequate workaround.

I'm using the [buddy-auth](https://funcool.github.io/buddy-auth/latest/#access-rules) library, and its associated access rules. The access rules are plain functions with one input, a `request`. Those functions are then incorporated into the call chain via a `wrap-access-rules` middleware.

Here's an example of basic buddy usage:
```clojure
(def rules [{:pattern #"^/admin/.*"
             :handler (fn [request]
                        ;; Check the request that this is in fact an admin user
                        ...))

(def app
  (-> handler
      (wrap-access-rules {:rules rules}))
```

Problem is: there's no way to pass dependencies from a duct endpoint to those functions. I'm assuming the whole point of duct was to keep the deps out of the request map.

Any advice? I'm happy to submit a patch, but I can't tell if it's a shortcoming of buddy, duct's design, or a limitation of ring's middleware protocol.

**Comment by weavejester** [comment]
I'm not sure why this is a problem. You could just write something like:

```clojure
(defn- make-rules [db]
  [{:pattern #"^/admin/.*", :handler (fn [request] ...)}])

(defn example-endpoint [{:keys [db]}]
  (-> (routes
       (GET "/admin/user/:id" [id] (admin-user db id))
       (GET "/admin/group/:id" [id] (admin-group db id)))
      (wrap-access-rules {:rules (make-rules db)})))
```

**Comment by kendagriff** [comment]
That's exactly what I tried before posting, but buddy throws an `IllegalArgumentError: Key must be an integer` when it calls the handler. I was assuming something within duct was changing the nature of the handler. I'll look at it a little closer...

**Comment by weavejester** [comment]
Duct doesn't try to do anything clever; it's just functions and closures and components. The `IllegalArgumentError` sounds like you might be passing the wrong thing somewhere.

**Comment by kendagriff** [comment]
Got it! Thanks for reassuring me on the path. Closing.
