### ISSUE TITLE
Improve clojurescript onboarding

### ISSUE THREAD

**Issue by pschorf** [weavejester/duct#13]
I recently started a new project using duct (my first time using clojurescript) and I was having a difficult time figuring out how to serve the generated js file until I changed system.clj to replace api-defaults with

`(meta-merge site-defaults {:static {:resources "APPNAME/public"}})`

Is it possible to generate that during the project setup? Or did I do it the wrong way?

**Comment by weavejester** [comment]
It already does add that into the `base-config`, but only if you use `+site` as well as `+cljs`.

Perhaps `+cljs` should imply `+site`? Or perhaps `+cljs` or `+site` add the static resources directory.

**Comment by weavejester** [comment]
I've decided to ensure that `+cljs` on its own adds the right resources path. It should work out of the box now, even if you miss out `+site` (though I'd still recommend both `+cljs` and `+site` for ClojureScript projects).

**Comment by pschorf** [comment]
Thanks!
