### ISSUE TITLE
Leaking middleware?

### ISSUE THREAD

**Issue by kendagriff** [weavejester/duct#15]
Is it possible for middleware wrapping `routes` in one endpoint to leak into the `routes` of a separate endpoint?

I think I'm seeing such behavior. If that's not right, I'll try posting a reproducible example.

**Comment by weavejester** [comment]
It depends what you mean by "leak".

There are two ways for middleware in one endpoint to affect another:

1. The body of a request is a mutable InputStream, so consuming the body in one endpoint will mean that body is not available for other endpoints. Ideally you should avoid putting middleware that does this in an endpoint.
2. If two endpoints are try and handle the same URL, then it's undefined which endpoint gets priority. This occurs if two endpoints have the same route, but also if one endpoint uses middleware that always returns a response, overriding the default fall-through. Authentication middleware often does this, if you're not using it with `compojure.core/wrap-routes`.

**Comment by kendagriff** [comment]
Okay, I think this example demonstrates well what I mean:

```clojure
(ns demo
  (:require [com.stuartsierra.component :as c]
            [compojure.core :refer [routes GET]]
            [duct.component.endpoint :refer [endpoint-component]]
            [duct.component.handler :refer [handler-component]]
            [ring.util.response :refer [response]]
            [ring.mock.request :as mock :refer [header]]))

(defn wrap-example [handler]
  (fn [req]
    (header req "X-EXAMPLE" true)))

(defn endpoint-1 [_]
  (-> (GET "/route-1" req
        (response ""))
      (routes)
      (wrap-example)))

(defn endpoint-2 [_]
  (-> (GET "/route-2" req
        (response ""))
      (routes)))

(defn new-system []
  (-> (c/system-map
        :app (handler-component {})
        :endpoint-1 (endpoint-component endpoint-1)
        :endpoint-2 (endpoint-component endpoint-2))
      (c/system-using
        {:app [:endpoint-1 :endpoint-2]})))

;; Evaling the code below mocks a request to /route-2,
;; invoking `endpoint-2`, and adding "x-example" to
;; the request header. But `wrap-example` only wraps `endpoint-1`.

(let [s (c/start (new-system))]
  (let [resp ((get-in s [:app :handler]) (mock/request :get "/route-2"))]
    (c/stop s)
    resp))

;; => {:server-port 80, :server-name "localhost", :remote-addr "localhost", :uri "/route-2", :query-string nil, :scheme :http, :request-method :get, :headers {"x-example" "true", "host" "localhost }}
```

In your response, you posed two circumstances under which the middleware will apply, the body or competing routes. The example above seems to avoid both those outcomes, but invoking either route will also invoke the middleware.

Again, I might be missing something obvious.

**Comment by weavejester** [comment]
Your middleware isn't passing the request onto the handler. You're returning the request as though it were a response instead, and because you're *always* returning a response from `endpoint-1`, you're effectively declaring that it handles all URLs and `endpoint-2` should be ignored.

You instead want something like:

```clojure
(defn wrap-example [handler]
  (fn [req]
    (handler (header req "X-EXAMPLE" true))))
```

**Comment by kendagriff** [comment]
Okay... the weakness is that poorly written middleware can infect the whole system (not just a single endpoint), BUT, that fixing the middleware restores order. Cool, thanks.

**Comment by weavejester** [comment]
Right. Each endpoint decides what routes its responsible for, so if you accidentally tell an endpoint to grab *all* routes, then your other endpoints won't fire.
