### ISSUE TITLE
How to structure routes having multiple endpoint components.

### ISSUE THREAD

**Issue by rcanepa** [weavejester/duct#26]
Hi James, I am building a real application on top of duct and I got stuck when I tried to extend my application to a couple of endpoints. I couldn't find a clear solution of how should I structure my code using components and at the same time having all the benefits of compojure-api/swagger. 

To continue working on my application, I had to create one main endpoint component, which imports routes tables from several endpoints (not real components), which of course it is not optimal. 

You can read more about this issue in a little discussion I had with another Duct user here:
http://yogthos.net/posts/2015-10-01-Compojure-API.html#comment-2400193168

Anyway, do you have recommendations on how to deal with this?

Thanks for Duct, I have learnt a lot from it!.

**Comment by weavejester** [comment]
Is this question specifically about the compojure-api project?

**Comment by rcanepa** [comment]
I would say no, because the confusion arises when dealing with endpoints as components, which can have dependencies, so normal routing tables ("pure" compojure-api tables) do not work in this schema (at least not with every endpoint as a component).

**Comment by weavejester** [comment]
No the question isn't about combining endpoints in general, or no the question isn't specifically about compojure-api?

It sounds like the problem is with how compojure-api happens to function, rather than any inherent issue with routing tables.

**Comment by rcanepa** [comment]
Ok, I will go in that direction then. This is my first application with Clojure, so most of things are new to me and the separation between concepts/libraries is not so clear to me yet.

Thanks.
