### ISSUE TITLE
Documentation for :duct { :ns-prefix <app> }

### ISSUE THREAD

**Issue by drusellers** [weavejester/duct#28]
I was reviewing my `project.clj` and noticed that there is a key in there that looks like `:duct { :ns-prefix app }` - after [reviewing the source](https://github.com/weavejester/duct/search?utf8=%E2%9C%93&q=ns-prefix) it looks like that this is a key I could remove from my project as its only needed when generating the project. 

This also makes me wonder, can duct work with an existing project? or is it really only for new projects?

Also, it might be worth documenting this key and what its used for.

**Comment by drusellers** [comment]
Ok, I did track down this lein plugin that I'm guessing is being used :) https://github.com/weavejester/lein-generate

**Comment by weavejester** [comment]
The `:duct {:ns-prefix prefix}` option is used for generators like `lein generate component` and `lein generate endpoint`. I've been considering moving the generators into the REPL, as the time taken to run Leiningen commands is prohibitive.

**Comment by drusellers** [comment]
@weavejester yeah, the `lean` commands can be a bear, but it is nice that you have taken the time to add these. I would love to add them to the documentation so that others can see them for sure. Is it worth documenting them, or are you considering removing them?

**Comment by weavejester** [comment]
They're documented in the project README, but I guess they could also be documented elsewhere as well.

If I do move the generators into the REPL, I'll likely still keep them in Lein as well, but executable via an alias. So something like:

    :aliases {"generate" ["run" "-m" "duct.generators/generate"]}

But I haven't come to any firm decisions around that.

Oh, and in answer to your question in your original post, all or just some of Duct can be used in existing projects, but they need to be converted manually.

**Comment by drusellers** [comment]
I don't see any thing in the README about using them as generators as well with `lein generate`. since I'm still so new to clojure i wasn't even aware of lein-generate to know that they could be shared. (sad panda)

**Comment by weavejester** [comment]
Sorry, I meant the README that's generated for the project, not the Duct README.

**Comment by weavejester** [comment]
Closing this since I've gotten rid of the `:ns-prefix` key in the project file.
