### ISSUE TITLE
Defaults key in HandlerComponent

### ISSUE THREAD

**Issue by danielsz** [weavejester/duct#32]
Hi, 

I was wondering what the purpose is of the `defaults` field in the Handler component record?

https://github.com/weavejester/duct/blob/4fa02a60abc82cff347470c2f1a5dfbbf70c8086/duct/src/duct/component/handler.clj#L24

I thought it might have something to do with default middleware, but it doesn't seem to be referenced by the component itself, and I saw the following approach to include default middleware:

```clojure
(def base-config
  {:app {:middleware [[wrap-not-found :not-found]
                      [wrap-webjars]
                      [wrap-defaults :defaults]]
         :not-found  (io/resource "errors/404.html")
         ; Remove anti-forgery from defaults. Add it only for the routes that need it.
         :defaults   (assoc-in site-defaults [:security :anti-forgery] false)}})
```

https://github.com/jstaffans/pay-me/blob/b7eb565959ec2548fed248a3509d592385f8a11c/src/clj/pay_me/system.clj#L17

My understanding is that this works because, as the wiki explains, "The keys will be substituted for their values in the component."

So I can't figure out what the use of `defaults` seems to be here.

**Comment by weavejester** [comment]
Ideally the issue tracker should be reserved for issues, rather than questions. I've created a Duct Google Group for that purpose, which is linked from the README.

The [Components](https://github.com/weavejester/duct/wiki/Components) wiki page gives an example of what this means, so just apply the same logic to the defaults middleware.

```clojure
{:middleware [wrap-defaults :defaults]]
 :defaults   (assoc-in site-defaults [:security :anti-forgery] false)}
```

Is the same as:

```clojure
{:middleware [#(wrap-defaults % (assoc-in site-defaults [:security :anti-forgery] false)]}
```

I'm not sure how to explain it anymore succinctly.

**Comment by danielsz** [comment]
Yes, this is nice and well understood. 

The feature is implemented by the `middleware-fn` in the `HandlerComponent`. 

I was wondering about the `defaults` field in the `defrecord` itself. Why is it necessary?

**Comment by weavejester** [comment]
Ah, I see what you mean now, and I can understand your confusion. That's actually a mistake. I'm not sure how it crept in there, but it shouldn't be there. The record should only have `middleware` as a key.

**Comment by danielsz** [comment]
:+1:

**Comment by weavejester** [comment]
Reopening because the `defaults` field needs to be removed.
