### ISSUE TITLE
Best practices for testing

### ISSUE THREAD

**Issue by kendagriff** [weavejester/duct#33]
I wanted to throw one of my common practices over the fence, and see if it's worth considering for addition to the library.

In each Duct project, I add a `test/system_test.clj` file. At its essence it has two pieces:

```clojure
(def test-config
  {:app ...})

(def config
  (meta-merge defaults environ test-config))
```

And, this for overloading the main system component...

```clojure
(defn new-system []
  (assoc (sys/new-system config)
              :my-component {}))
```

It's basically my standard way of implementing stubs for tests, which are often different from what I want from my live development environment.

Have I missed an obvious solution that already exists in Duct?

**Comment by weavejester** [comment]
This is for testing the entire system, rather than an individual component or endpoint, right?

**Comment by kendagriff** [comment]
Yes. I'll admit the primary use is for integration-like tests, incorporating components across the system. I've even written a macro that helps me test with little setup:

```
(with-system (new-system) {:keys [db]}
  (is ...)
```

The first argument accepts whatever system I care to test, the second deconstructs it, the third is my assertions. It starts the system, runs the body, then cleans up after itself.

Thoughts?

**Comment by weavejester** [comment]
I think it's a sound idea. I tend to have a `test/<project>/system_test.clj` file as well.

Integrating it into the template might be a little tricky because of the need to have a test database in order for it to work with projects that use a database. I guess a `TEST_DATABASE_URL` environment variable might be useful to complement `DATABASE_URL`.

**Comment by kendagriff** [comment]
You mean like this, right?

`system_test.clj`:
```
(def test-config
  {:database-url (env :test-database-url})
```

`user.clj`:
```
(def dev-config
  {:database-url (env :database-url})
```

More or less?

P.S. If this is a low-use feature addition, no worries; just something I add regularly. My testing tends to coalesce around high-risk or opaque functions, which are often multi-component, so the ability to bring the system up and down easily has saved me a lot of time.
