### ISSUE TITLE
Multiple POST endpoints bug

### ISSUE THREAD

**Issue by lerouxrgd** [weavejester/duct#34]
Hi,

First of all thank you for `duct` it's a very simple and useful framework for structuring Clojure webapps !
However I run into an issue when trying to assemble multiple endpoints containing at least one POST handler.
I am also using `compojure-api` for defining handlers and I hope I am using it and `duct` correctly.

I re-created my issue with a minimal repo:
https://github.com/lerouxrgd/debug-duct
Basically I created it like this:
```
lein new duct debug-duct
```
Adding compojure-api dependency to `project.clj`
```clj
[metosin/compojure-api "0.23.1"]
```
First endpoint `plus.clj`
```clj
(defn plus-endpoint [sys]
  (api   
   (context* "" []
             (POST* "/plus" []
                    :return {:total Long}
                    :body-params [x :- Long, y :- Long]
                    :summary "x+y with body-parameters"
                    (ok {:total (+ x y)})))))
```
Second endpoint `minus.clj`
```clj
(defn minus-endpoint [sys]
  (api
   (context* "" []
             (POST* "/minus" []
                    :return {:total Long}
                    :body-params [x :- Long, y :- Long]
                    :summary "x-y with body-parameters"
                    (ok {:total (- x y)})))))
```
Combining them in `system.clj`
```clj
(defn new-system [config]
  (let [config (meta-merge base-config config)]
    (-> (component/system-map
         :app  (handler-component (:app config))
         :plus (endpoint-component plus-endpoint)
         :minus (endpoint-component minus-endpoint)
         :http (jetty-server (:http config)))
        (component/system-using
         {:http [:app]
          :app  [:plus :minus]}))))
```
Starting it at the repl
```
lein repl
(go)
```
And finally, the bug when trying to test it:
```
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" -d "{
  \"y\": 1,
  \"x\": 2
}" "http://localhost:3000/plus"
```
Gives me
```
{"errors":"(not (map? nil))"}
```

I tried to remove one endpoint like this:
```clj
(defn new-system [config]
  (let [config (meta-merge base-config config)]
    (-> (component/system-map
         :app  (handler-component (:app config))
         :plus (endpoint-component plus-endpoint)
         #_:minus #_(endpoint-component minus-endpoint)
         :http (jetty-server (:http config)))
        (component/system-using
         {:http [:app]
          :app  [:plus #_:minus]}))))
```
Restarting it at the REPL
```
(reset)
```
Now when sending the same POST request with curl I get the expected response:
```
{"total":3}
```

After some debugging I realised that I get a `"(not (map? nil))"` because `:body` is actually empty; which I confirmed by trying to `slurp` its `#object[org.eclipse.jetty.server.HttpInputOverHTTP 0x5c8389 "HttpInputOverHTTP@5c8389"]`.

However I am not sure to understand why the body input stream gets consummed somewhere before my handler.

Is it a wrong manipulation from me, or is there something fishy with multiple endpoints/handlers and POST body input stream ?

**Comment by lerouxrgd** [comment]
I seems to be fixed in the latest versions, sorry for the troubles.

**Comment by weavejester** [comment]
Sorry for the late reply. This sounds more like a problem with compojure-api than Duct. By "fixed in the latest versions", do you mean the latest versions of compojure-api?

**Comment by lerouxrgd** [comment]
I am using [metosin/compojure-api "0.23.1"] in both case.
I just updated [duct "0.4.5"] --> [duct "0.5.7"]
Quickly checking the code (might be wrong), I suspect something around here ?
https://github.com/weavejester/duct/blob/0.4.5/duct/src/duct/component/handler.clj#L5
https://github.com/weavejester/duct/blob/0.5.7/duct/src/duct/component/handler.clj#L5

**Comment by weavejester** [comment]
The difference between the two code bases is whether or not the routes have a specific ordering. I can't think why that would make a difference to compojure-api, but I don't know a lot about the internals of that project.

**Comment by lerouxrgd** [comment]
Actually I realised that `[duct "0.5.7"]` fixed it for my original project (not sure why...), but in the debug repo (https://github.com/lerouxrgd/debug-duct) I still have only POST to /minus working (POST to /plus gives me the empty map error message).
I'll try to look more into `compojure-api` internals.
