### ISSUE TITLE
Reloadable Routes

### ISSUE THREAD

**Issue by kendagriff** [weavejester/duct#7]
Any guidance on how I might modify duct to allow for reloadable endpoints (e.g. inspect the routes in the browser without resetting the system each time)?

**Comment by weavejester** [comment]
Could you explain your reasons for wanting this?

**Comment by kendagriff** [comment]
Just looking for a "Save the file and refresh" type solution for developing a web app. Right now in Vim, I'm switching to the `'user` namespace and running `(reset)` after re-evaluating the system.

Have I missed something obvious?

**Comment by weavejester** [comment]
Evaluating `(reloaded.repl/reset)` will re-evaluate all changed files and restart the system. If you're using fireplace.vim, you should be able to hook up a key or command to evaluate that. I believe you can also use vim's autocmd capabilities to run a command in response to a buffer save event.

**Comment by kendagriff** [comment]
Of course! Thank you!
