### ISSUE TITLE
Component Registry

### ISSUE THREAD

**Issue by kendagriff** [weavejester/duct#9]
I've been working with Duct for about two months now – with two microservices in production – and I believe it's the _best_ way I've seen yet for building webapps in Clojure. I've also made a few of my own duct components (for example: https://github.com/banzai-inc/ring-sentry-component), and noticed you've created a small suite already.

I wonder if a component registry (a section of the README or a Github wiki?) might help the cause? I'd happily contribute mine, or help keep a list...

**Comment by weavejester** [comment]
Thanks for the vote of confidence! Your idea for a list of compatible components is a good one. The wiki seems the best place for it, as it can be edited independent of the repository, but I'll add a link to the README as well.

Would "Compatible Libraries" be a good title in your estimation?

**Comment by kendagriff** [comment]
Perfect!

**Comment by weavejester** [comment]
Added a wiki page. Feel free to add in your own libraries.

**Comment by kendagriff** [comment]
Final question: Is a component like this appropriate for the list: https://github.com/banzai-inc/fixtures-component? It's not duct-oriented, per se, but it feeds into the purpose of duct – it's primary application is a web-app.

For example, I'm frequently including the [ring-jetty-component](https://github.com/weavejester/ring-jetty-component) in my duct applications. Is that not also relevant to a budding new duct user?

**Comment by weavejester** [comment]
Yeah, any component would be good to add, as long as it isn't tied somehow to another framework.
